name: MoistMeter
description: ML Based Rainwater Harvesting Planner
author: Cenentury0941
specification_version: 1.0
prototype_version: 2.0
date: "2024-03-04"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: src/install_dependencies.py
    kernel: python3
    cpu: 2
    memory: 4

  - type: run_session
    name: Download Data
    script: src/download_data.py
    kernel: python3
    cpu: 2
    memory: 4

  - type: run_session
    name: Train Model
    script: src/train_model.py
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: Application to serve UI
    short_summary: Create an application to serve the UI
    subdomain: moistmeter
    script: app/backend/app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
